Repository eclipse-tractusx/portal-frontend, pull requests merged in 2023-07, with the labels that each got.

#110 feat(usecase): implement usecase backend logic
  CHANGELOG.md
  DEPENDENCIES
  src/assets/locales/de/main.json
  src/assets/locales/en/main.json
  src/components/pages/UsecaseParticipation/UsecaseParticipation.scss
  src/components/pages/UsecaseParticipation/index.tsx
  src/features/store.ts
  src/features/usecase/usecaseApiSlice.ts
  src/types/Config.tsx
Labels: priority

#122 bugfix(notification): isread user action
  CHANGELOG.md
  src/components/pages/NotificationCenter/NotificationItem.tsx
Labels: priority

#137 fix(app-release-process): selected values disappears
  CHANGELOG.md
  src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
  src/components/shared/basic/ReleaseProcess/ContractAndConsent/index.tsx
  src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx
Labels: rel 1.6.0

#136 updates(connector): managed connectors
  CHANGELOG.md
  src/assets/locales/de/main.json
  src/assets/locales/en/main.json
  src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
  src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx
  src/components/pages/EdcConnector/index.tsx
  src/features/connector/connectorApiSlice.ts
Labels: priority, rel 1.6.0

#132 fix(app-release): add privacy policy validation
  CHANGELOG.md
  src/assets/locales/de/main.json
  src/assets/locales/en/main.json
  src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
Labels: rel 1.6.0

#177 bugfix(admin credentials): added roles for admin credential
  src/types/Config.tsx
Labels: priority
