Repository eclipse-tractusx/portal-frontend, pull requests merged in 2023-11, with the labels that each got.

#331 Fix/cplp 3191/enable osp prototype
  src/assets/locales/en/idp.json
  src/components/overlays/AddIDP/index.tsx
  src/components/overlays/OSPConsent/OSPConsentContent.tsx
  src/components/overlays/OSPConsent/index.tsx
  src/components/overlays/OSPConsent/style.scss
  src/components/overlays/OSPRegister/OSPRegisterContent.tsx
  src/components/overlays/OSPRegister/OSPRegisterNext.tsx
  src/components/overlays/OSPRegister/index.tsx
  src/components/overlays/UpdateIDP/index.tsx
  src/components/pages/IDPManagement/IDPList.tsx
  src/components/pages/OSPManagement/index.tsx
  src/features/admin/networkApiSlice.ts
  src/services/AccessService.tsx
  src/types/Config.tsx
  src/types/Patterns.ts
Labels: priority

#342 update(company role): update osp translations
  CHANGELOG.md
  src/assets/locales/de/main.json
  src/assets/locales/en/main.json
Labels: priority, rel 23.12

#304 chore(deps): upgrade dependencies
  DEPENDENCIES
  yarn.lock
Labels: rel 23.12

#343 fix(company role): change company role showing invalid deselect
  CHANGELOG.md
  src/components/overlays/UpdateCompanyRole/index.tsx
  src/components/pages/CompanyRoleUpdate/index.tsx
Labels: priority, rel 23.12

#338 bugfix(registration): country code
  CHANGELOG.md
  src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/index.tsx
  src/features/admin/registration/types.ts
Labels: rel 23.12

#348 bugfix(tech user): fix duplicate entry issue
  CHANGELOG.md
  src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
  src/features/admin/serviceApiSlice.ts
Labels: rel 23.12

#345 fix(subscription): sorting fixes
  CHANGELOG.md
  src/components/shared/templates/Subscription/index.tsx
Labels: rel 23.12

#339 feat(user bulk): error handling
  CHANGELOG.md
  src/assets/locales/de/main.json
  src/assets/locales/en/main.json
  src/components/overlays/AddMultipleUser/index.tsx
  src/features/appManagement/userManagementApiSlice.ts
Labels: rel 23.12

#340 feat(idp): user migration error handling
  CHANGELOG.md
  src/components/overlays/AddusersIDP/index.tsx
Labels: rel 23.12

#341 bugfix(notification): change navigation link to service marketplace
  src/assets/locales/de/notification.json
  src/assets/locales/en/notification.json
  src/components/pages/NotificationCenter/NotificationItem.tsx
Labels: rel 23.12

#344 bugfix(technical integration): error message fix
  CHANGELOG.md
  src/assets/locales/de/main.json
  src/assets/locales/de/servicerelease.json
  src/assets/locales/en/main.json
  src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
Labels: rel 23.12

#351 updates(app detail): ui changes
  CHANGELOG.md
  src/components/pages/AppDetail/components/AppDetailHeader/AppDetailHeader.scss
  src/components/pages/AppDetail/components/AppDetailHeader/index.tsx
Labels: rel 23.12

#365 feat(change documents): connect post and delete endpoints
  CHANGELOG.md
  src/assets/locales/de/main.json
  src/assets/locales/en/main.json
  src/components/pages/AppOverview/ChangeDocuments.tsx
  src/features/appManagement/apiSlice.ts
Labels: priority, rel 23.12

#370 fix(techuser-details): solve crash issue
  src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx
Labels: bug, rel 23.12

#373 feat(app and service): update subscription logic
  CHANGELOG.md
  DEPENDENCIES
  src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/index.tsx
  src/components/shared/templates/Subscription/SubscriptionElements.tsx
  src/features/appSubscription/appSubscriptionApiSlice.ts
Labels: priority, rel 23.12
