Repository eclipse-tractusx/portal-frontend, pull requests merged in 2025-05, with the labels that each got.

#1512 refactor(app marketplace): remove axios library use
  src/assets/locales/de/main.json
  src/assets/locales/en/main.json
  src/components/pages/AppDetail/AppDetailHeader/index.tsx
  src/components/pages/AppMarketplace/AppListSection/index.tsx
  src/components/pages/AppMarketplace/FavoriteSection/FavoriteItem.tsx
  src/components/pages/AppMarketplace/FavoriteSection/index.tsx
  src/features/apps/details/actions.ts
  src/features/apps/details/apiTestdata.ts
  src/features/apps/details/slice.ts
  src/features/apps/favorites/actions.ts
  src/features/apps/favorites/api.ts
  src/features/apps/favorites/apiSlice.ts
  src/features/apps/favorites/slice.ts
  src/features/apps/index.ts
  src/features/apps/marketplaceDeprecated/actions.ts
  src/features/apps/marketplaceDeprecated/api.ts
  src/features/apps/marketplaceDeprecated/apiSlice.ts
  src/features/apps/marketplaceDeprecated/apiTestdata.ts
  src/features/apps/marketplaceDeprecated/slice.ts
  src/features/info/search/actions.ts
  src/features/store.ts
Labels: Improvement

#1570 feat(connector): only show available tech user
  src/components/pages/EdcConnector/AddConnectorOverlay/ConnectorInsertForm.tsx
  src/features/admin/serviceApiSlice.ts
Labels: priority

#1569 feat(Connector): added a view for provided connector
  src/assets/locales/de/main.json
  src/assets/locales/en/main.json
  src/components/pages/EdcConnector/edcProvidedConnectorTableColumns.tsx
  src/components/pages/EdcConnector/index.tsx
  src/features/connector/connectorApiSlice.ts
Labels: enhancement, priority

#1457 feat(auto-setup): add fields for auth in auto setup
  src/assets/locales/de/main.json
  src/assets/locales/en/main.json
  src/components/overlays/AddServiceProvider/index.tsx
  src/components/overlays/AddServiceProvider/style.scss
  src/components/shared/basic/Input/ValidatingInput.tsx
  src/features/serviceProvider/serviceProviderApiSlice.ts
Labels: enhancement, priority

#1554 feat(service/app subscription): add new autosetup url
  src/assets/locales/de/main.json
  src/assets/locales/de/servicerelease.json
  src/assets/locales/en/main.json
  src/assets/locales/en/servicerelease.json
  src/components/overlays/ActivateServiceSubscription/index.tsx
  src/components/pages/AppSubscription/ActivateSubscriptionOverlay/index.tsx
  src/components/shared/templates/Subscription/SubscriptionElements.tsx
  src/components/shared/templates/Subscription/index.tsx
  src/features/appSubscription/appSubscriptionApiSlice.ts
  src/features/serviceManagement/apiSlice.ts
Labels: priority

#1584 fix: adjust CSV upload logic to match template structure
  public/template_app_role_upload.csv
  src/components/pages/AppOverview/AddRolesOverlay.tsx
Labels: bug

#1602 fix: sectioner contain width changed to auto-100%
  src/components/pages/TechnicalUserManagement/style.scss
Labels: bug

#1612 fix: pull fresh technical user - own connector
  src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx
Labels: bug

#1611 fix: adjust row cell logic to work on all browsers
  src/components/pages/CompanySubscriptions/index.tsx
Labels: bug

#1603 fix: user role selection for app access
  src/components/overlays/AddAppUserRoles/AppRoles.tsx
Labels: bug
